SOURCES = [
    {
        "id": "noticiasdatv-televisao",
        "name": "Notícias da TV — Televisão",
        "list_url": "https://noticiasdatv.uol.com.br/canal/televisao-1",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "link_path_contains": "/canal/televisao-1/",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-reality-show",
        "name": "Notícias da TV — Reality Show",
        "list_url": "https://noticiasdatv.uol.com.br/reality-show",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "link_path_contains": "/reality-show/",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-esportes-na-tv",
        "name": "Notícias da TV — Esportes na TV",
        "list_url": "https://noticiasdatv.uol.com.br/canal/esportes-na-tv-34",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-colunistas",
        "name": "Notícias da TV — Colunistas",
        "list_url": "https://noticiasdatv.uol.com.br/colunistas",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-audiencias",
        "name": "Notícias da TV — Audiências",
        "list_url": "https://noticiasdatv.uol.com.br/canal/audiencias-4",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "link_path_contains": "/canal/audiencias-4/",
        "scan_items": 30,
        "max_items": 50,
    },    
    {
        "id": "natelinha-televisao",
        "name": "NaTelinha — Televisão",
        "list_url": "https://natelinha.uol.com.br/televisao",
        "item_selector": ".noticia:has(a[href*='/televisao/'])",
        "title_selector": ".titulo a",
        "link_selector": "a[href*='/televisao/']",
        "scan_items": 50,
        "max_items": 50,
    },
    {
        "id": "natelinha-audiencias",
        "name": "NaTelinha — Audiências",
        "list_url": "https://natelinha.uol.com.br/audiencias",
        "container_selector": ".noticiasList",
        "item_selector": ".noticia",
        "title_selector": ".titulo a",
        "link_selector": "a",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "natelinha-colunas",
        "name": "NaTelinha — Colunas",
        "list_url": "https://natelinha.uol.com.br/colunas",
        "item_selector": ".noticia:has(a[href*='/colunas/'])",
        "title_selector": ".titulo a",
        "link_selector": "a[href*='/colunas/']",
        "scan_items": 50,
        "max_items": 50,
    },    
    {
        "id": "natelinha-tv-historia",
        "name": "NaTelinha — TV História",
        "list_url": "https://natelinha.uol.com.br/tv-historia",
        "container_selector": ".noticiasList",
        "item_selector": ".noticia",
        "title_selector": ".titulo a",
        "link_selector": "a",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "ricksouza",
        "name": "X — Rick Souza",
        "list_url": "https://fxtwitter.com/RickSouza/feed.xml?count=100&with_replies=1",
        "container_selector": "#tweets-tabs",
        "item_selector": ":scope > div",
        "title_selector": ".activity-descp > p:first-of-type",
        "link_selector": ".main-user-dts1 a[href*='/status/']",
        "scan_items": 100,
        "max_items": 50,
        "twitter_filter": True,
        "rss_xml": True,
    },
]
