SOURCES = [
    {
        "id": "noticiasdatv-televisao",
        "name": "Notícias da TV — Televisão",
        "list_url": "https://noticiasdatv.uol.com.br/canal/televisao-1",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-reality-show",
        "name": "Notícias da TV — Reality Show",
        "list_url": "https://noticiasdatv.uol.com.br/reality-show",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-esportes-na-tv",
        "name": "Notícias da TV — Esportes na TV",
        "list_url": "https://noticiasdatv.uol.com.br/canal/esportes-na-tv-34",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-colunistas",
        "name": "Notícias da TV — Colunistas",
        "list_url": "https://noticiasdatv.uol.com.br/colunistas",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
    {
        "id": "noticiasdatv-audiencias",
        "name": "Notícias da TV — Audiências",
        "list_url": "https://noticiasdatv.uol.com.br/canal/audiencias-4",
        "item_selector": ".item-artigo",
        "title_selector": ".titulo_capa",
        "link_selector": "a",
        "date_selector": ".artigo-data",
        "scan_items": 30,
        "max_items": 50,
    },
]
    {
        "id": "natelinha-televisao",
        "name": "NaTelinha — Televisão",
        "list_url": "https://natelinha.uol.com.br/televisao",
        "container_selector": "section",
        "item_selector": ".noticia",
        "title_selector": ".titulo a",
        "link_selector": "a",
        "scan_items": 30,
        "max_items": 50,
    },
